version: '3.8'

services:
  fastapi-app:
    build: .  # Uses the Dockerfile in the current directory
    container_name: book-keeping-container  # Custom container name
    ports:
      - "8000:8000"  # Maps container port 8000 to host port 8000
    env_file:
      - .env  # Loads environment variables securely
    volumes:
      - .:/app  # Mounts current directory inside the container
    restart: unless-stopped  # Ensures container restarts unless manually stopped
